const path = require("path");
const fs = require("fs");
const os = require("os");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");

function getHttpsOptions() {
  // Read the dev certificates generated by office-addin-dev-certs directly.
  // This avoids the CA-trust verification step, which pops an interactive
  // confirmation dialog on first use (blocking automated/dev-server startup).
  const certDir = path.join(os.homedir(), ".office-addin-dev-certs");
  const key = path.join(certDir, "localhost.key");
  const cert = path.join(certDir, "localhost.crt");
  const ca = path.join(certDir, "ca.crt");
  if (!(fs.existsSync(key) && fs.existsSync(cert))) {
    throw new Error(
      "HTTPS certificates not found in " +
        certDir +
        ". Run: npx office-addin-dev-certs install"
    );
  }
  return {
    key: fs.readFileSync(key),
    cert: fs.readFileSync(cert),
    ca: fs.existsSync(ca) ? fs.readFileSync(ca) : undefined,
  };
}

module.exports = async () => {
  let devServer = {};

  // Only resolve the dev certificates when running the dev server.
  // Builds (`npm run build`) never need HTTPS.
  if (process.env.WEBPACK_SERVE === "true") {
    devServer = {
      port: 3000,
      host: "localhost",
      https: getHttpsOptions(),
      allowedHosts: "all",
      static: {
        directory: path.resolve(__dirname, "dist"),
      },
      headers: {
        "Access-Control-Allow-Origin": "*",
      },
      hot: false,
    };
  }

  return {
    entry: {
      taskpane: "./src/taskpane/taskpane.js",
    },
    devtool: "source-map",
    output: {
      path: path.resolve(__dirname, "dist"),
      filename: "[name].js",
      clean: true,
    },
    devServer,
    plugins: [
      new HtmlWebpackPlugin({
        filename: "taskpane.html",
        template: "./src/taskpane/taskpane.html",
        chunks: ["taskpane"],
      }),
      new HtmlWebpackPlugin({
        filename: "commands.html",
        template: "./src/commands/commands.html",
        chunks: [],
      }),
      new CopyWebpackPlugin({
        patterns: [
          { from: "assets", to: "assets" },
          { from: "src/taskpane/taskpane.css", to: "taskpane.css" },
        ],
      }),
    ],
  };
};